export default [
  {
    "id": "tt0103064",
    "title": "Terminator 2: Judgment Day",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0088247",
    "title": "The Terminator",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0181852",
    "title": "Terminator 3: Rise of the Machines",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTk5NzM1ODgyN15BMl5BanBnXkFtZTcwMzA5MjAzMw@@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0438488",
    "title": "Terminator Salvation",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BODBlOTJhZjItMGRmYS00YzM1LWFmZTktOTJmNDMyZTBjMjBkXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt1340138",
    "title": "Terminator Genisys",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMjM1NTc0NzE4OF5BMl5BanBnXkFtZTgwNDkyNjQ1NTE@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt6450804",
    "title": "Terminator: Dark Fate",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BNzhlYjE5MjMtZDJmYy00MGZmLTgwN2MtZGM0NTk2ZTczNmU5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0095483",
    "title": "Lady Terminator",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTg5NTA1NzEtNWNiNy00ZTc4LWJhZTgtYmJkODZhYWI3NmQ4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0098321",
    "title": "Terminator II",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BNDNlMWExNTMtMmJkYi00OTg2LTlmY2EtZThjYzA1ZWI2NzFkXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0199849",
    "title": "Ninja Terminator",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMGZiNTczNWItOTdmYy00OTFjLWIwOWUtMmE3Y2QyNzBmZDJkXkEyXkFqcGdeQXVyNzg3NjQyOQ@@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0112320",
    "title": "Alien Terminator",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTc3NjY4YjItZWFjYi00MzQxLWE1M2UtZGU1OTBjZWZlZjkyXkEyXkFqcGdeQXVyMjI4NzM3NTM@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0100531",
    "title": "Russian Terminator",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BYjBmM2YyMGMtZTMxZS00OWZlLWEyYzQtNzUyYWFmMWM2N2M1XkEyXkFqcGdeQXVyMjUyNDk2ODc@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0271049",
    "title": "The Making of 'Terminator 2: Judgment Day'",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BZmIwZTFmNDItNjBjOC00ZjFmLTkwNzEtNTdlZWM1MGIwMDU4XkEyXkFqcGdeQXVyMTEwNDU1MzEy._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0108313",
    "title": "Terminator Woman",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTcwMTE0MTgzMV5BMl5BanBnXkFtZTcwOTYyOTAwMQ@@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0267719",
    "title": "The Making of 'Terminator'",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTQ3MzE5NTI0Nl5BMl5BanBnXkFtZTgwNDE1OTk1MDE@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0365601",
    "title": "Other Voices: Back Through Time: Creating 'The Terminator': Cast & Crew Recollections",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTU4NjA2NTgzNF5BMl5BanBnXkFtZTYwNTIzNzc5._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0365473",
    "title": "The Making of 'The Terminator': A Retrospective",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTU4NjA2NTgzNF5BMl5BanBnXkFtZTYwNTIzNzc5._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0391240",
    "title": "Inside 'Terminator 3: Rise of the Machines'",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BMTY2MTc4MzcwNF5BMl5BanBnXkFtZTcwNTUzODE1Mg@@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0368004",
    "title": "The Making of 'Terminator 2 3D'",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BYmEwOTU0ZDktNjlmMy00ODJlLWIxOGMtOTk2MTc1NzBiZTA4XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt6068550",
    "title": "Terminator 2 Remake with Joseph Baena: Bad to the Bone",
    "plot": "",
    "image": "https://m.media-amazon.com/images/M/MV5BYzc0YmVmYzEtNzA4MS00OTI2LWJlMDgtMTdmZjY3ODhhZmM1XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  },
  {
    "id": "tt0420017",
    "title": "No Fate But What We Make: 'Terminator 2' and the Rise of Digital Effects",
    "plot": "",
    "image": "",
    "actors": "",
    "genre": "",
    "runtime": "",
    "language": "",
    "writer": "",
    "director": "",
    "year": ""
  }
]